### ISSUE TITLE
Make database inteface

### ISSUE THREAD

**Issue by trquoccuong** [arrowjs/ArrowjsCore#1]
with sql, postgres, sqlite use sequelize to connect db
with mongo use moogoose

**Comment by TechMaster** [comment]
Put it low priority at the moment

**Comment by trquoccuong** [comment]
need : import, associate

**Comment by TechMaster** [comment]
What is "associate"?

**Comment by trquoccuong** [comment]
sequelize have associate models. I log some function maybe need in next phase
