### ISSUE TITLE
Arrowjs on Windows has issue 

### ISSUE THREAD

**Issue by lethanhtrung2020** [arrowjs/ArrowjsCore#25]
Hi,
I use ArrowJS on Windows (7,8,10), all have same issues (see attached file for ref.)

![arrowjs_bug](https://cloud.githubusercontent.com/assets/14961790/16899123/7a6b7076-4c22-11e6-96ec-da659f884c23.png)

Below are steps to install ArrowJS CMS on Windows
-----------------
1. Install nodejs (4.x hoac 6.x)
2. Install python 2.7 
3. Install visual studio 2015 (selected C++ in order to build buffertools)
4. Install redis for windows
5. Install postgres for windows
6. Run npm install (admin privileged)
7. Change config (db and redis)
Note: changed fakeredis to redis already
-----------------
Please help to check.
Thanks

**Comment by paduvi** [comment]
Hi @lethanhtrung2020 
I have tried follow your steps and run ArrowCMS but can't reproduce the error.

The error stack coming from ExpressJS, maybe it's caused because there are more than 1 response in your route flow. Can you provide your code at route "/" here?

**Comment by lethanhtrung2020** [comment]
Hi @paduvi 
You can refer to videos below to reproduce the error

https://www.youtube.com/watch?v=eKQfEJ5SiOU&feature=youtu.be
https://www.youtube.com/watch?v=fry9-U3Dl14&feature=youtu.be

Thanks
Trung

**Comment by paduvi** [comment]
I have tried your code on my Windows 10 PC and it still workings
![image](https://cloud.githubusercontent.com/assets/15514657/16905959/9089cd56-4cd8-11e6-81d8-7e14c692f7a1.png)

Try `git clone https://github.com/arrowjs/CMS.git` then run default code example again. If it don't have any errors, let's have a look back at your modified code and used middlewares

**Comment by lethanhtrung2020** [comment]
Hi @paduvi 
We use CMS ArrowJS cloned from latest version but issue still there.
We can offer you a remote access to have more information if you prefer.
Trung

**Comment by paduvi** [comment]
okay, contact me on Skype: phanducviet3695

**Comment by TechMaster** [comment]
Let' team view to see what happened

**Comment by lethanhtrung2020** [comment]
The issue is solved by using redis for windows, provided by MSOpentech (https://msopentech.com/blog/tag/redis/)
Thanks @paduvi for your support.
